name: Run Bash Script

on:
  push:
    branches: [ main ]

jobs:
  bash_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x script.sh

      - name: Run the script
        run: ./script.sh
